### ISSUE TITLE
BT-1451-Contract (Winner Decision Date)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#110]
Related to https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1214474190, the draft guidance maps this field to `Award.date`.

In eForms, the field is a child of `SettledContract` (a contract in OCDS) rather than `LotResult` (an award in OCDS) and a `LotResult` refers 'forward' to one or more `SettledContract`s. Therefore, if one `LotResult` refers to more than one `SettledContract` and each `SettledContract` has a different winner decision date, there will be several different dates mapped to the same `Award.date` field.

The simplest solution would be to choose a single winner decision date to map to `Award.date`, e.g. the most recent winner decision date. However, that would involve some data loss.

An alternative could be to update the guidance in https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1254446750 to create one award for each `<efac:SettledContract>` in `<efac:LotResult>`. However, that would lead to repetition, lose the 1:1 relationship between a `LotResult` and an `Award`, and make it difficult to identify which award relates to which `SettledContract`:

> **Get the awards for the LotResult**
> Get the `Award` objects in `awards` whose `.relatedLots` contain the value of the XPath `ancestor::efac:LotResult/efac:TenderLot​/cbc:ID`. If none exist yet, for each `<efac:SettledContract>` in `<efac:LotResult>`:
> * Add an `Award` to `awards`
> * Set its `.id` sequentially
> * Add the value of the XPath `ancestor::efac:LotResult/efac:TenderLot​/cbc:ID` to its `.relatedLots`

Also, I'm not sure if it's possible to publish a notice containing a `LotResult` and to later add `SettledContract`s, in which case the OCDS data for the initial notice would contain only one award which would then need to be 'split' when the settled contracts are added.

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
Let's keep 1-1 for LotResult and Award and SettledContract and Contract.

Let's use the earliest Winner Decision Date as the one that survives. Otherwise, we can end up with contracts that are concluded before the award was made.

I had hoped the two BTs might be non-overlapping, but that's not the case. Looking at the original `fields.json`, BT-1451-Contract (Winner Decision Date) is only mandatory on [notice type](https://github.com/OP-TED/eForms-SDK/blob/main/notice-types/notice-types.json) 36, which is "Design contest result notice – general directive, design". That said, it's still optional on every form on which BT-145-Contract (Contract Conclusion Date) can appear.

Winner Decision Date is:

> The date of the official decision choosing the winning tender.

Contract Conclusion Date is:

> The date when the contract was concluded. Typically, this is the date when the last contractual party signed the contract. However, if no contract is signed, then the date of contract conclusion may correspond to other dates (e.g. the date when the buyer notified the winning tenderer). The date of contract conclusion is always later than the end of the standstill period and only once any evidence submitted by the winner has been verified.

I don't understand why Winner Decision Date hangs off SettledContract, since a contract is not settled at the time of the decision, but rather at the time of its conclusion, and given that BT-142-LotResult (Winner Chosen) hangs off LotResult. I suspect that maybe they put it on SettledContract for practical rather than ontological reasons.

**Comment by duncandewhurst** [comment]
Sounds good. Thanks!

**Comment by duncandewhurst** [comment]
Draft guidance for winner decision date:

> For each `ancestor::efac:NoticeResult/efac:LotResult` with an `/efac:SettledContract/cbc:ID` equal to the value of `ancestor::efac:SettledContract/cbc:ID`:
> * Get the `Award` object in `awards` whose `.id` is equal to the LotResult's `/cbc:ID`. If none exists yet:
>   * Add an `Award` to `awards`
>   * Set its `.id` to the value of the LotResult's `/cbc:ID`
>   * Add the value of the LotResult's `/efac:TenderLot​/cbc:ID` to the award's `.relatedLots`
> * If the award's `.date` is not yet set or if the winner decision date is earlier than the award's `.date`, map to the award's `.date`. Otherwise, discard.

**Comment by duncandewhurst** [comment]
I've updated `guidance.yaml` so I'll close this issue.
