### ISSUE TITLE
OPT-170-Tenderer: Group lead indicator

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#139]
This is a boolean field used when there is more than one organization under `efac:TenderingParty` to indicate which is the 'lead' party. It is a required field if more than one tenderer is present. We have no equivalent concept in OCDS with all tenderers featuring in the bid's `tenderers` array but with no cardinality.

Potential options include:
1. stating cardinality in the guidance, i.e. list the tenderer with `GroupLeadIndicator` = "true" first in the `bids.tenderer` array.  This is a bit opaque but doesn't require adding anything to the standard.
2. Add a new code to `partyRoles`, "leadTenderer"
3. Add a boolean field e.g. `leadTenderer`, to `Organization`

@jpmckinney my feeling is the first option is preferable but happy to go with another.

**Comment by jpmckinney** [comment]
Thinking through (2): I figure it's unlikely that the same tenderer is a group lead for one bid (e.g on lot A) and not group lead on another bid (e.g. on lot B). So, this should work and be easier to implement.

Since OPT-170-Tenderer is not required, we don't want to imply that every first-listed tenderer is a group lead. So, we should go with (2).

**Comment by odscjen** [comment]
Great, I've also added in common guidance for getting the organization for a tenderer https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1332267966
