### ISSUE TITLE
OPT-301-Tenderer Subcontractor and MainContractor

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#144]
These are two of the technical identifiers that can be found under `<efac:TenderingParty>` within a `<efac:NoticeResult>`. 

The `tenderer`s are defined, then the `subcontractor`s are given along with which of the `tenderer`s are responsible for subcontracting that `subcontractor`.

So in the example below ORG-0005 and ORG-0008 are the `tenderer`s. Both are planning on subcontracting out some of the work to ORG-0012, and ORG-0005 will also be subcontracting some work out to ORG-0015.

```
<efac:NoticeResult>
    <efac:TenderingParty>
        <cbc:ID schemeName="tendering-party">TPA-0003</cbc:ID>
        <efac:Tenderer>
            <cbc:ID schemeName="organization">ORG-0005</cbc:ID>
            <efbc:GroupLeadIndicator>true</efbc:GroupLeadIndicator>
        </efac:Tenderer>
        <efac:Tenderer>
            <cbc:ID schemeName="organization">ORG-0008</cbc:ID>
            <efbc:GroupLeadIndicator>false</efbc:GroupLeadIndicator>
        </efac:Tenderer>
        <efac:SubContractor>
            <cbc:ID schemeName="organization">ORG-0012</cbc:ID>
            <efac:MainContractor>
                <cbc:ID schemeName="organization">ORG-0005</cbc:ID>
            </efac:MainContractor>
            <efac:MainContractor>
                <cbc:ID schemeName="organization">ORG-0008</cbc:ID>
            </efac:MainContractor>
        </efac:SubContractor>
        <efac:SubContractor>
            <cbc:ID schemeName="organization">ORG-0015</cbc:ID>
            <efac:MainContractor>
                <cbc:ID schemeName="organization">ORG-0005</cbc:ID>
            </efac:MainContractor>
        </efac:SubContractor>
    </efac:TenderingParty>
</efac:NoticeResult>
```

To capture which organizations involved are subcontractors we can simply create a new role, e.g. `subcontractor`, to add to the `.roles` array, but if this is all we do we'll lose the specifics of the relationships between the `tenderer`s and `subcontractor`s in situations where there is more than one `tenderer`. I can imagine there are use cases where retaining this information is important, particularly for supply chain monitoring.

My initial thought is that we could add an array, e.g. `subcontractors` to `awards.subcontracting` and the array would be made up of `Organization` objects linking to the subcontractor organization and the associated main contractor.

```json
{
    "awards": [
        {
            "subcontracting": {
                "subcontractors": [
                    {
                        "subcontractor": {
                            "name": "Subcontractors are us",
                            "id": "ORG-0015"
                        },
                        "mainContractor": {
                            "name": "A1 Tenderer",
                            "id": "ORG-0005"
                        }
                    }
                ]
            }
        }
    ]
}
```

@jpmckinney @duncandewhurst any thoughts?

**Comment by duncandewhurst** [comment]
There's a related issue in the standard repository, but it seems like eForms has more detail than the examples we've seen previously:

* https://github.com/open-contracting/standard/issues/392

Regarding the modelling:

* Tendering party appears on `LotTender` so I think that this information should be on `Bid` rather than `Award` in OCDS. Otherwise, the information about subcontractors for unsuccessful bidders would be lost.
* `Bid.subcontracting.subcontractors` sounds good.
* I think we should use `tenderer` rather than `mainContractor` in keeping with the terminology used elsewhere in OCDS.
* I don't like having a property named `subcontractor` on the  objects in the `subcontractors` array, since those objects are subcontractors themselves. Alternatively, we could introduce a `subcontractorReference` object, which would be an `organisationReference` with an extra field to reference the tenderer to which the subcontractor relates.

Here's an example with the above changes:

```json
{
  "bids": [
    {
      "details": {
        "subcontracting": {
          "subcontractors": [
            {
              "id": "ORG-0015",
              "name": "Subcontractors are us",
              "tenderer": {
                "id": "ORG-0005",
                "name": "A1 Tenderer"
              }
            }
          ]
        }
      }
    }
  ]
}
```
Other alternatives I considered were:

* Nest the information in `parties`, i.e. `Organization.subcontractors`, but I don't think we want to add that field to all organizations.
* Nest the information within the `Bid.tenderers` array, e.g. `Bid.tenderers.subcontractors`, in which case we'd need to introduce a `tendererReference` object. I actually think that seems like a more natural place to put the information, but it would require a change to the bid extension and would come at the expense of keeping all the subcontracting information together under `subcontracting`.

**Comment by odscjen** [comment]
> Tendering party appears on LotTender so I think that this information should be on Bid rather than Award in OCDS. Otherwise, the information about subcontractors for unsuccessful bidders would be lost.

But the `efac:TenderingParty/efac:SubContractor/cbc:ID` field only appears in the `efac:NoticeResult/`, so information about subcontractors for unsuccessful bidders isn't provided. The subcontractors themselves only appear once the lot has been awarded to a tendering party. The only subcontracting information provided at the bid/[LotTender stage](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#lotTenderSection) is:

- Subcontracting Value Known (BT-730),
- Subcontracting Percentage Known (BT-731),
- Subcontracting Value (BT-553),
- Subcontracting Percentage (BT-555),
- Subcontracting Description (BT-554),
- Subcontracting (BT-773) (a yes/no boolean).

I like the change to `subcontractors` with the `tenderer` organization reference and calling them `tenderer`s rather than `mainContractor`s makes sense. This would need to be an array however as more than one `tenderer` can be the `mainContractor` for a `subcontractor` (which I forgot to include in my own suggestion) and so `tenderers` maybe makes more sense.

So given all that how about:

```json
{
    "awards": [
        {
            "subcontracting": {
                "subcontractors": [
                    {
                        "id": "ORG-0012",
                        "name": "Subcontractors are us",
                        "tenderers": [
                            {
                                "id": "ORG-0005",
                                "name": "A1 Tenderer"
                            },
                            {
                                "id": "ORG-0008",
                                "name": "B2 Tenderer"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

**Comment by jpmckinney** [comment]
OCDS 1.0 didn't have any model for bids, so fields were added to Award.

However, process-wise, it is more correct for an Award to reference a Bid as awarded/successful. What information is made available doesn't really affect the correct modelling. For this issue, my understanding is that the bidders (the main contractors) disclose their subcontractors in their bid to the buyer. Later, only the details of the winning bid are published.

In principle, the data model should, as much as possible, [provide only one way to answer a question](https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#guidelines). Presently, if bid data is available, the suppliers can be determined from the bid data OR the award data. If we were to go back and redo things, we'd consider eliminating suppliers from Award (this could be a proposal for OCDS 1.2 – and maybe there are use cases for having both the bid data and award data on suppliers.)

So, I would put this under the bid.

As for how to model the relationships: the eForms SDK looks very flexible, such that a subcontractor can be related to one or more main contractors. This relation is not really a property of the subcontractor – since it is only true for this specific bid (it's maybe even possible that different bids by different main contractors use the same subcontractors). Instead, we need an object to represent the "subcontracting relationship" to which we can imagine adding other properties (e.g. the value).

I figure a good name for the relationship can be `subcontracts`.

**Comment by duncandewhurst** [comment]
> For this issue, my understanding is that the bidders (the main contractors) disclose their subcontractors in their bid to the buyer. Later, only the details of the winning bid are published.

I can't find anywhere where it is specified that only the details of subcontractors for the winning bid are published. If subcontracting information can be disclosed for unsuccessful bids, then we'll need to make it clear that `subcontracts` are the relationships that the tenderers expect to enter into if the bid is successful. Looking at the field names alone, I feel that `subcontracts` implies actual, existing, contracts. Otherwise, your proposed modelling looks good.

> But the `efac:TenderingParty/efac:SubContractor/cbc:ID` field only appears in the `efac:NoticeResult/`, so information about subcontractors for unsuccessful bidders isn't provided. The subcontractors themselves only appear once the lot has been awarded to a tendering party. 

I'm not sure that follows since `LotTender` only appears in `efac:NoticeResult` too and `LotTender` can represent either a successful or unsuccessful bid, depending on the value of `/cbc:TenderResultCode` in the `LotResult` that references the `LotTender`.

> The only subcontracting information provided at the bid/[LotTender stage](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#lotTenderSection) is:
> 
>     * Subcontracting Value Known (BT-730),
> 
>     * Subcontracting Percentage Known (BT-731),
> 
>     * Subcontracting Value (BT-553),
> 
>     * Subcontracting Percentage (BT-555),
> 
>     * Subcontracting Description (BT-554),
> 
>     * Subcontracting (BT-773) (a yes/no boolean).

There's also Tendering Party ID Reference (OPT-310), which references the `TenderingParty`, which can include subcontractors.

**Comment by jpmckinney** [comment]
I think the EU doesn't disclose individual data about unsuccessful bids – only aggregate data – in order to address competition concerns.

Given that it is a bid, I think it is implied that the subcontract relationships are proposed/tentative. Anyhow, this can be made clear in the description – unless we can think of a better field name.

**Comment by odscjen** [comment]
All good points and you're right @duncandewhurst that subcontractors for all bids in `LotTender` are there in the `TenderingParty` section, I'd missed that, but I think @jpmckinney is right that only successful bids are detailed. 

>I'm not sure that follows since LotTender only appears in efac:NoticeResult too and LotTender can represent either a successful or unsuccessful bid, depending on the value of /cbc:TenderResultCode in the LotResult that references the LotTender.

I don't think this is right. `TenderResultCode` says whether or not a winner was chosen, it applies to the Lot/Procedure not to each individual Bid (the slightly inconsistent way the word "tender" is used is unhelpful here). So in this [example CAN notice](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_24_maximal.xml) for `LotResult` RES-0001 the `TenderResultCode` is "selec-w" = "At least one winner was chosen.". It then lists 2 bids in `efac:LotResult/efac:LotTender` (TEN-0001 and TEN-0002) yet the value for `<efac:ReceivedSubmissionsStatistics>efbc:StatisticsCode listName="received-submission-type">tenders</efbc:StatisticsCode>` is "9", so there were 9 bids received but only 2 are listed in the `LotResult` both of which are named in the `SettledContracts` section for the 2 contracts listed in `LotResult`, "CON-0001" and "CON-0002", implying that only the winning bids are provided in detail.

The only issue I have with the proposed modelling is that `TenderingParty` can contain more than one subcontracting relationship, which is presumably representative of more than one subcontract, but the rest of the subcontracting details provided aren't split up into individual subcontracts within the bid, they're aggregate, e.g. `TermAmount` states that 50000 EUR is going to be the value that is subcontracted but if 2 subcontractors are listed there's nothing to say how much of that is going to each. So while I see the logic of having a `subcontract` object to which other properties can be added, in the case of eForms all of the other properties that are provided aren't at this level, they're at the level above and having the object called `subcontracts` would to me imply that the rest of the details of that subcontract should be there, and that any details outside of that array are about a different subcontract. To make is clearer that this object is just about establishing what the various relationships are it could be `subcontractRelationships`? But this then wouldn't work as a generic object to which subcontract specific properties could be added. I suppose it depends on if there are use cases where information specific to individual subcontracts is published?

**Comment by duncandewhurst** [comment]
> I don't think this is right. `TenderResultCode` says whether or not a winner was chosen, it applies to the Lot/Procedure not to each individual Bid (the slightly inconsistent way the word "tender" is used is unhelpful here). So in this [example CAN notice](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_24_maximal.xml) for `LotResult` RES-0001 the `TenderResultCode` is "selec-w" = "At least one winner was chosen.". It then lists 2 bids in `efac:LotResult/efac:LotTender` (TEN-0001 and TEN-0002) yet the value for `<efac:ReceivedSubmissionsStatistics>efbc:StatisticsCode listName="received-submission-type">tenders</efbc:StatisticsCode>` is "9", so there were 9 bids received but only 2 are listed in the `LotResult` both of which are named in the `SettledContracts` section for the 2 contracts listed in `LotResult`, "CON-0001" and "CON-0002", implying that only the winning bids are provided in detail.

Ah, good sleuthing. That confirms what @jpmckinney said so I stand thoroughly corrected :-)

> I suppose it depends on if there are use cases where information specific to individual subcontracts is published?

I think this is likely to be something that we need to support in the future so the proposed model makes sense to me:

- `subcontracting` - aggregate data about all the subcontracts of a given contract
- `subcontracting.subcontracts` - data on individual subcontracts

**Comment by odscjen** [comment]
Great, thanks both, I'll use the `bids.details.subcontracting.subcontracts` model in the guidance.yaml then :)

**Comment by odscjen** [comment]
closing as updated guidance.yaml
