### ISSUE TITLE
OPT-301: TenderReceipt and TenderEval roles

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#149]
From https://github.com/open-contracting/european-union-support/issues/141, eForms introduces two subroles that need new codes. I propose the following codes to align with OCDS terminology:

* Requests to participate/tender recipient organization (Organization receiving requests to participate/tenders): 'submissionBody'
* Requests to participate processing/tender evaluation organization (Organization processing requests to participate/tenders): 'evaluationBody'

@jpmckinney does that sound good?

**Comment by duncandewhurst** [comment]
In keeping with the other OPT-301 codes, rather than adding a field to link these roles to specific lots, I'll reuse the boilerplate from #145.

**Comment by jpmckinney** [comment]
I think either 'evaluator' or 'evaluationBody' are fine. The only '*Body' in OCDS 1.1 is reviewBody. We can keep it and change 'mediationBody' (new in 1.2) to 'mediator' if we prefer the latter style.

Instead of 'submissionBody' we'd have to change it to something like recipient / receiver / receiptBody – since the noun ought to describe the body's action (review, mediation, etc.). Recipient seems the more appropriate word, but it can also have a meaning of a recipient of an *award* or prize, whereas receiver doesn't have any potentially confusing connotations. So I'd favor something with "receiver" if we use it on its own without any modifier.

That said, just using "receiver" is a bit vague, since all sorts of things can be received (requests to participate, bids, complaints, etc.). In 1.2, we use "submission" to stand for "requests to participate and/or bids", but 'submissionReciever' reads a bit vague, still. eForms uses `TenderRecipientParty`, with a note to say that whether what's received is a request to participate or a bid is given by the context. We could do the same thing, like 'bidReciever' / 'bidRecipient', but I'd rather avoid having to clarify in documentation that requests to participate are also covered.

So, those are a few options with pros/cons, not sure which to go with or if there are some other options.

**Comment by duncandewhurst** [comment]
> the noun ought to describe the body's action (review, mediation, etc.)

Ah yes, that makes sense.

I prefer 'submissionReceiver' or 'submissionReceiptBody' to align with the name of `submissionMethodDetails` and the use of 'submission' in the description of several other fields.

Regarding choosing whether to include the 'Body' suffix, on the one hand, it seems like unnecessary fluff, but on the other hand, I think 'evaluation' and 'mediation' are more common terms than 'evaluator' and 'mediator' so it might be easier for readers to quickly grasp the meaning 'evaluationBody' and 'mediationBody'.

Overall, my gut sense is that the following would be best:

- reviewBody
- mediationBody
- evaluationBody
- sumissionReceiptBody

**Comment by duncandewhurst** [comment]
Noting that https://github.com/open-contracting/european-union-support/issues/143 also proposes some new codes with a 'Body' suffix.

**Comment by jpmckinney** [comment]
I'm happy with submissionReceiptBody.

**Comment by duncandewhurst** [comment]
I've updated `guidance.yaml`.
