### ISSUE TITLE
Fill in empty URLs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#156]
i.e. occurrences of `(<>)`

**Comment by odscjen** [comment]
Having a quick check through and some of this instances are references to [mapping tables](https://github.com/open-contracting/european-union-support/tree/main/output/mapping/eforms/mapping-tables). But some of the other mapping table references don't have any url's empty or otherwise.

Do references to mapping tables require a url link (which at the moment would be the github link) or not? I'm assuming that ultimately these tables will be hosted on the OCDS EU profile page and that would be the link we wanted to use?

**Comment by jpmckinney** [comment]
BT-749-Lot has "[Concatenate it with BT-750-Lot Selection Criteria Description.]" (and vice versa).

I assume these are meant to link to each other, so I've added that link.

**Comment by jpmckinney** [comment]
I've now added URLs for all Markdown links that lacked a target.
