### ISSUE TITLE
OPP-080-Tender: Remove/resolve "[TED guidance]" in eForms guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#158]

**Comment by odscjen** [comment]
This was waiting on an answer from https://github.com/OP-TED/eForms-SDK/discussions/248 as per https://github.com/open-contracting/european-union-support/issues/131.

There's still been no answer.

As the details of a bid are only published if it is successful we can assume that there will always be a contract associated with any `LotTender` that this BT (the others mentioned in https://github.com/open-contracting/european-union-support/issues/131) so we could just map them all to `contract`?

@jpmckinney @duncandewhurst

**Comment by jpmckinney** [comment]
Yes, I think it is either the contract or the award (whichever makes more sense based on how other BTs have been mapped).

**Comment by odscjen** [comment]
Looking at the other BT's that occur in `LotTender` there's a mix as to where they are mapped to. The majority are mapped to `bids.details`, there are 3 mapped otherwise:
* BT-160-Tender: efbc:RevenueBuyerAmount -> `contracts.implementation.charges` 
* BT-162-Tender: efbc:RevenueUserAmount -> `contracts.implementation.charges` 
* BT-163-Tender: efbc:ValueDescription -> `awards.valueCalculationMethod`

These 3 all follow the TED mapping and even though they all belong together in eForms I think the separation in OCDS makes sense.

So there's no clear common mapping between `contract` and `award` so for OPP-080 and the other unmapped terms from `LotTender` (discussed in #131) I think it makes the most sense to map them to `contract` as per the TED mapping.

Does that seem alright @jpmckinney?

**Comment by jpmckinney** [comment]
Yes, sounds good to map to contract. Thanks for checking!
