### ISSUE TITLE
Additional fields to proposed extension mapping

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#167]
I've mapped the additional OCDS fields reported by the lint command to extensions in a [spreadsheet](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=1483744764).

Most additional fields map to existing extensions. I've proposed [new extensions](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=1828468637) for some fields. 

@jpmckinney do you want to review the mapping and check that you're happy with it? In particular, whether any of the proposed new extensions can be bundled into the European Union extension

If you prefer not to review yet, we can move fields between extensions as needed as part of the PR review process. Either way, in the meantime, we can start working on updating extensions for which the mappings are clear.

cc @odscjen

**Comment by jpmckinney** [comment]
I think the new extensions related to 1.2 fields can perhaps be bundled into a "futures" extension. These are:

* Contract identifiers (new extension for OCDS 1.1 only, field already added in OCDS 1.2)
* Document languages (new extension)
* Exclusion grounds (new extension)
* Framework agreements (new extension)
* Tender identifiers (new extension for OCDS 1.1, field already added in OCDS 1.2)

The following can probably go into the EU extension, as not yet sure whether they can be reused:

* Accessibility criteria (new extension)
* Document translations (new extension)
* eDelivery (new extension)

Then:

* tender/lots/otherRequirements/securityClearance -> I figure can go into Other Requirements instead of EU

**Comment by duncandewhurst** [comment]
Sounds good! I've made those updates.

To avoid confusion with [futures](https://www.investopedia.com/terms/f/futures.asp), I wonder if we should choose a different name for that extension. We could just call it the OCDS 1.2 extension or perhaps 'Future fields' would be sufficient.

**Comment by odscjen** [comment]
@jpmckinney we've mapped out the [additional codes](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=578320437) reported by the lint now as well, do you want to check that you're happy with these?

**Comment by jpmckinney** [comment]
> To avoid confusion with [futures](https://www.investopedia.com/terms/f/futures.asp), I wonder if we should choose a different name for that extension. We could just call it the OCDS 1.2 extension or perhaps 'Future fields' would be sufficient.

Maybe ocds_1_2_draft_extension, to clearly suggest it's not stable.

**Comment by jpmckinney** [comment]
> @jpmckinney we've mapped out the [additional codes](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=578320437) reported by the lint now as well, do you want to check that you're happy with these?

Looks good. I left some comments. I assume some of the values in the "Additional code" column might change in our codelists, to match our style guide.

**Comment by odscjen** [comment]
I realised the spreadsheet didn't contain any of the new codes that we've added to mapping tables so I've added a sheet in with that. 

@duncandewhurst I added the new codes to the bottom of the [Additional code mapping](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=578320437) sheet but I couldn't work out how to get the `Sustainability` new codes to show up in the [Summary by extension](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=850849696) sheet?

**Comment by duncandewhurst** [comment]
Thanks! The new codes should be showing up in that sheet now. The issue was that the sustainability extension was identified by its URL in some sheets and by its name elsewhere.

**Comment by odscjen** [comment]
@jpmckinney just wanting to double check if we're still wanting to map  `documents.unofficialTranslation` to the EU extension rather than the [Documentation details](https://extensions.open-contracting.org/en/extensions/documentation_details/master/) extension? As an additional bit of information about a document it does feel like it would be a good fit to that extension unless we're sure the EU will be the only users of it?

**Comment by jpmckinney** [comment]
Documentation details sounds fine to me!

**Comment by odscjen** [comment]
great, thanks, I'll update the extension tracking spreadsheet and the guidance.yaml

**Comment by duncandewhurst** [comment]
I think that this issue can be closed now as we're using the [spreadsheet](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=1619313430) to keep a track of authoring and updating extensions.
