### ISSUE TITLE
BT-631: Dispatch invitation interest - communciation/invitationToConfirmInterest/startDate?

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#168]
Working on the update to the [Communication extension](https://extensions.open-contracting.org/en/extensions/communication/master/) and BT-631-Lot has been mapped to the new field `communication.inviationToConfirmInterest.startDate` as first suggested in https://github.com/open-contracting/european-union-support/issues/55#issue-972614724.

Does it need the `startDate` though? To me having a start date implies the possibility of an end date which certainly in the eForms doesn't look like it's an option as the definition of BT-631 is "The estimated date of dispatch of the invitations to confirm interest." so it's a single date, much like `futureNoticeDate` rather than a period like `documentAvailabilityPeriod` (both from Communication). 

Should we leave this as `startDate` (and therefore have it as a `Period` in the extension to allow more flexibility for potential non-EU uses) or change it to just a single date-time field?

@jpmckinney

**Comment by jpmckinney** [comment]
Yes, a simple date is fine.

We need to clearly disambiguate `futureNoticeDate` from this other date.

futureNoticeDate is "used for planning notices [a.k.a. PINs] (PIN Profile excluded) to specify when the competition notice will be published." https://docs.ted.europa.eu/eforms/1.3/schema/notice-information.html#futureNoticeSection

This new date is: "For PIN call for competition notices, the estimated date of dispatch of the invitations to confirm interest" https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#interestInvitationSection

The two can never occur together, as I understand, since a PIN that is also a call for competition (the second case) would never need to specify a competition notice (the first case). (And a PIN that is *not* also a call for competition could specify the first case, but wouldn't qualify the preconditions for the second case.)

In terms of the meaning of "invitation to confirm interest", I think a PIN that is also a call for competition requires potential suppliers to submit interest, and then the buyer will communicate with them directly (i.e. without a contract notice).

For the name, I can't think of anything better than `invitationToConfirmInterestDate`.

**Comment by odscjen** [comment]
great, that all makes sense thanks
