### ISSUE TITLE
Docs folder missing

### ISSUE THREAD

**Issue by bjornjorgensen** [open-contracting/european-union-support#40]
Hi, I have the XML files for the Norwegian Doffin. It's the same as TED. And I well make JSON files of it. 
I'm trying to run code with ours data (not mine) but i dont find the docs folder 

for i in 01 02 03 04 05 06 07 08 12 13 14 15 20 21 22 23 24 25; rake table LANGUAGE=EN FILES=F$i > path/to/european-union/docs/forms/F$i.md; end
for i in 01 02; rake table LANGUAGE=EN FILES=MOVE FORM=T$i > path/to/european-union/docs/forms/T$i.md; end

When i run 
for i in 01 02 03 04 05 06 07 08 12 13 14 15 20 21 22 23 24 25; rake table LANGUAGE=EN FILES=F$i > /home/bjorn/source/european-union-support/output/content/F$i.md; end

I get 
index of key in data:
6

omit: icar_noticeref
ignore: internets
enumerations: maintype_ministry
additional: false
rake aborted!
unexpected key: nutscode
/home/bjorn/source/european-union-support/tasks/table.rake:210:in `block (2 levels) in <top (required)>'
/home/bjorn/source/european-union-support/tasks/table.rake:59:in `each'
/home/bjorn/source/european-union-support/tasks/table.rake:59:in `block in <top (required)>'
Tasks: TOP => table
(See full trace by running task with --trace)

**Comment by jpmckinney** [comment]
Hi @bjornjorgensen, this repository is for internal use, and all it does is help us prepare the documentation at https://standard.open-contracting.org/profiles/eu/master/en/

If you are looking for software to convert TED XML to OCDS JSON, there is no public code that we know of. However, Proactis has implemented this for Scotland, and the UK has also implemented this (so that their systems continue to operate without access to TED). The OCDS Helpdesk supported and reviewed both implementations. To get in touch, please email data@open-contracting.org
