### ISSUE TITLE
BT-740: Buyer Contracting Entity

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#65]
eForms has a code list for organization roles and subroles. On top of these roles, buyers can be (or not) 'contracting entity' via the BT-740 (Buyer Contracting Entity) boolean.

Definition of 'buyer' in the [eForms regulation](https://eur-lex.europa.eu/eli/reg_impl/2019/1780/oj):

> Buyer refers to a contracting authority, a contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority; unless the above mentioned are an association of organisations that is not an organisation in itself, in which case each individual organisation is considered a 'buyer'.

Definition of 'contracting authorities' in the directive 2014/24/EU:

> contracting authorities means the State, regional or local authorities, bodies governed by public law or  associations formed by one or more such authorities or one or more such  bodies governed by public law.

I couldn't find an official definition of 'contracting entity'.

'contracting entity' is not mentioned in related issues (https://github.com/open-contracting/standard/issues/825, https://github.com/open-contracting/standard/issues/571) 

I'm not sure how to tie BT-740 back to OCDS roles (buyer, procuringEntity):

-  what role does the organization get if BT-740 is 'not-cont-ent' (`False`)?
- if it's 'cont-ent' (`True`)?

Any idea @JachymHercher?

**Comment by jpmckinney** [comment]
I think "Contracting entity" is specific to 2014/25/EU: https://eur-lex.europa.eu/eli/dir/2014/25/oj

**Comment by ColinMaudry** [comment]
> If you are a contracting entity, you will be a buyer. If you are not a contracting entity, you could be anything (including a buyer).

Right, but since this BT not the primary way to designate the buyer, and this concept is specific to EU, I think we should mirror this boolean in the EU extension.

**Comment by JachymHercher** [comment]
Yes, I guess that makes sense. (In eForms, the contracting entity is essentially a subcode of Buyer. It's split into a separate field I guess mainly to avoid having Organization Role repeatable. Since `partyRole` is an array, this isn't really an issue in OCDS.)

**Comment by ColinMaudry** [comment]
Legal basis is enough to contextualize the data. We can discard this BT.

**Comment by JachymHercher** [comment]
If it were that easy! For Directive 2014/25/EU (sectoral) this is indeed the case, but for the Defence (2009/81/EC) and Concessions (2014/23/EU) Directives you can have either and that's where you need the field. (That's why eForms themselves actually don't contain this field for the Sectoral Directive, but just for the Defence and Concessions.)

**Comment by jpmckinney** [comment]
Boo. I guess we can use https://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/ since this is not a role, but more the identity of the buyer.

**Comment by JachymHercher** [comment]
> Boo. I guess we can use https://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/ since this is not a role, but more the identity of the buyer.

I'm not sure. If we want to join this boolean under a different codelist, then I think it should be under [BT-11 (Buyer Legal Type)](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/buyer-legal-type), as this codelist contains the other "subcodes" from eForms' definition of buyer (i.e. defence contractor, international organization, organization awarding a subsidized contract).

**Comment by jpmckinney** [comment]
I think we model the buyer legal type using the organization classification extension: https://standard.open-contracting.org/profiles/eu/latest/en/forms/F01/#I.4

**Comment by jpmckinney** [comment]
Noting that presently the draft mapping uses party roles but should use organization classification per discussion.

**Comment by duncandewhurst** [comment]
The current draft mapping for BT-740 references a buyer contracting types mapping table:

> [Get the organization for the buyer](common-operations.md#get-the-organization-for-the-buyer) and add a `Classification` object to its `.details.classifications` array. Map to the classification's `.id`, set its `.description` to the code according to the mapping in \[buyer contracting types mapping table\], and set its `.scheme` to 'TED_BUYER_TYPE'.

Is the following table sufficient?

| buyer-contracting-type code | `.description` |
| -- | -- |
| cont-ent | Contracting entity |
| not-cont-ent | Not contracting entity |

**Comment by jpmckinney** [comment]
I think so, yes.

In Slack I had written:

It looks like eForms invented a [buyer-contracting-type](https://github.com/OP-TED/eForms-SDK/blob/main/codelists/buyer-contracting-type.gc) codelist just for this BT, with the codes cont-ent and not-cont-ent. As usual, eForms is more explicit, having a not-cont-ent code instead of just an absence of a cont-ent code.

BT-11 uses the buyer-legal-type codelist, which we named TED_CA_TYPE to be consistent with the older TED mapping. That said, I’d be fine with adding another entry to the extension’s [classification scheme list](https://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/codelists/) for buyer-legal-type.

As for BT-740, since we need a new scheme for cont-ent (buyer-contracting-type), we might as well map not-cont-ent, rather than be implicit as usual. And, yes, we can add the scheme to the extension’s list.

**Comment by duncandewhurst** [comment]
Ah, yes. Apologies, I forgot that this was discussed on Slack!

**Comment by jpmckinney** [comment]
No worries - just taking the opportunity to log the discussion here for posterity :)

**Comment by jpmckinney** [comment]
Looks like this was mapped as a classification as discussed (buyer-contracting-type.csv).
