### ISSUE TITLE
BT-40 Selection Criteria Second Stage Invite

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#72]
Definition:

> The criteria (or criterion) will (only) be used to select the candidates to be invited for the second stage of the procedure (if a maximum number of candidates was set).

Shall I understand it as: 

> The criteria or criterion will only be used to select the candidates to be invited for the second stage of the procedure if a maximum number of candidates was set. (all parenthesis removed)

or:

> The criteria or criterion will be used to select the candidates to be invited for the second stage of the procedure, **and possibly for the rest of the procedure**. If a maximum number of candidates was set, they will **only** be used to select the candidates to be invited for the second stage.

or something else?

Any idea @JachymHercher?

**Comment by JachymHercher** [comment]
> The criteria or criterion will only be used to select the candidates to be invited for the second stage of the procedure if a maximum number of candidates was set. (all parenthesis removed)

This is closer. Most of the parentheses don't really make a difference, the only one is the "(only)" whose point is that the selection criterion which is marked with this field might not apply in some cases (see below). It's probably confusing rather than enlightening.

___

Context: Typically, you want to only talk to suppliers that meet a certain baseline, so you set a selection criterion to "suppliers must have a turnover of at least 1M EUR / year". Additionally, you sometimes want to make sure you don't end up talking to 100 suppliers, so you need some sort of condition that you'll only talk to those that seem to meet the baseline the best ("only 5 suppliers will be invited to the second round, they will be chosen based on the turnover selection criterion, i.e. the 5 suppliers with the highest turnover go to the next round"). If you use the criterion for this type of reduction, you are supposed to mark it using BT-40. (What the "(only)" refers to is the case when you wouldn't use it for the first use above, but you would use it for the second one. It's legally possible, but I can't think of when you would actually want to do it.)

**Comment by ColinMaudry** [comment]
OK. I propose we add a `.forReduction` boolean field to the [Selection criterion](https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension ) object, with the following description:

> The selection criterion is used to reduce the number of selected suppliers to a maximum number.

**Comment by jpmckinney** [comment]
Sounds good, I'm just wondering about the name of the field. Terms somewhat related to this concept are in https://extensions.open-contracting.org/en/extensions/secondStageDescription/master/schema/

Maybe `reductionOnly` ?

**Comment by ColinMaudry** [comment]
As @JachymHercher comments it:

> It's legally possible, but I can't think of when you would actually want to do it.

Meaning that a buyer may use a selection criterion only for reducing the number of tenderers to a given number, but in the great majority of cases, a selection criterion that is used for reduction is also used as a normal selection criterion (to filter apt tenderers).

This is why adding `only` in the semantics of the fields would probably not match the main use of this term.

**Comment by jpmckinney** [comment]
Oh, sorry, I had misunderstood the semantics. So it's a criterion that will be used to reduce the number of qualified bidders IF the number of qualified bidders exceeds some threshold.

I'm not sure about `forReduction` since we don't have a lot of fields of the form `prepositionNoun`, and "for" can sometimes be confused with "exclusively for".

How's `reductionCriterion`? I share some of my thought process for alternatives below, but this is the best I can come up with. It's a bit repetitive having the word "criterion" appear in a field of a criterion, but I think it works.

---

I'm trying to think of adjectives like capable, relevant, appropriate, applicable, but none of them seem very clear (yet). Or maybe something along the lines of permitted, allowed...

Alternatively we can use a verb phrase like `mayBeUsedForReduction` which addresses the above concern, but has the downside of being rather long and awkward. Maybe `supportsReduction`...

**Comment by ColinMaudry** [comment]
I'll go with `reductionCriterion` for now, we'll make sure the definition clarifies the semantics.

**Comment by jpmckinney** [comment]
Mapped as discussed. I can't think of a better term. I kind of like `forReduction` except that it's typically read as "explicitly for" (which is an issue as there might not be any reduction needed, and the criterion would still be applied).

**Comment by jpmckinney** [comment]
I kind of like `forReduction` except that it's typically read as "exclusively for", which is an issue as there might not be any reduction needed, and the criterion would still be applied. That said, if it were exclusively for reduction, we'd model it in a separate field. The primary semantics are that it's a selection criterion, and secondarily it can be "for reduction". So, I'll rename it.
