### ISSUE TITLE
BT-65 Subcontracting Tender Obligation

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#75]
BT-65 "Subcontracting Tender Obligation" is an array of codes ([values](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-obligation)). 

Description:

> An obligation to be met by the tenderer concerning subcontracting.

In OCDS, the [subcontracting extension](https://extensions.open-contracting.org/en/extensions/subcontracting/master/) has `tender.subcontracting.description`, but it rather matches better with BT-554 Subcontracting Description. 

We could cram BT-65 Subcontracting Tender Obligation in `tender.subcontracting.description`, asking implementers to append the label or labels from [the codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-obligation).

Or we add a new field to the subcontracting extension.

Related to #74

**Comment by ColinMaudry** [comment]
I think this one works well with `.subcontracting.description`.

**Comment by ColinMaudry** [comment]
Here is the guidance:

> If different from 'none', retrieve the [label of the code](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-obligation), and map it to the lot's `.subcontracting.description`

**Comment by duncandewhurst** [comment]
It seems to me that `lots.subcontractingTerms` is a better fit for BT-65 since `SubcontractingTerms` is about obligations rather than the actual subcontracting that will happen. `lots.subcontractingTerms` is otherwise unmapped in eForms.

@jpmckinney, what do you think?

**Comment by duncandewhurst** [comment]
Similarly, I'm unsure if the following fields actually belong in `Subcontracting` rather than `SubcontractingTerms`:

* `.competitiveMaximumPercentage`: "The maximum percentage of the contract value that the procuring entity requires the supplier to subcontract to third parties through a competitive procedure."
* `.competitiveMinimumPercentage`: "The minimum percentage of the contract value that the procuring entity requires the supplier to subcontract to third parties through a competitive procedure."

**Comment by jpmckinney** [comment]
The subcontracting extension had percentages on the award, because that is when this information was disclosed in TED notices.

BT-64 and BT-729  Subcontracting Obligation Minimum / Maximum in the regulation are on the PIN and Contract Notice, so that's new.

Since these now appear before award/contract, and since tender only has `subcontractingTerms`, it makes sense to add corresponding fields to `SubcontractingTerms`.

**Comment by duncandewhurst** [comment]
Sounds good.

Were you happy with my suggestion of mapping BT-65 Subcontracting Tender Obligation to `lots.subcontractingTerms`?

> `lots.subcontractingTerms` is otherwise unmapped in eForms.

Noting that in https://github.com/open-contracting/european-union-support/issues/74, I've suggested that we also map BT-651 Subcontracting Tender Indication to `subcontractingTerms`.

**Comment by duncandewhurst** [comment]
Great. I've updated `guidance.yaml` for BT-65. At the same time, I updated the eForms guidance and OCDS examples for BT-64 and BT-729 to match the approach used in BT-555 (divide by 100 to get a percentage). PR for changes to the subcontracting extension: https://github.com/open-contracting-extensions/ocds_subcontracting_extension/pull/6
