### ISSUE TITLE
BT-1252 Direct Award Justification Previous Procedure Identifier, related process code list

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#77]
BT-1252 Direct Award Justification Previous Procedure Identifier enables to link a procedure that justifies the use of a direct procedure. 

> An identifier of a previous procedure that justifies the use of a procedure which allows directly awarding contracts, i.e. justifying a procedure that does not require publishing a call for competition in the Official Journal of the European Union.

This BT would typically work well with the `tender.relatedProcesses` array, but I'm not sure [the existing codes](https://standard.open-contracting.org/staging/1.2-dev/en/schema/codelists/#related-process) fit the bill.

Is a new code necessary?

**Comment by jpmckinney** [comment]
`relationship` is an array, so we can use "prior" and maybe add a new code for the narrower semantics.

**Comment by ColinMaudry** [comment]
It may be unsuccessful, but it's not the only the reason to use a direct procedure.Here are [the justification codes](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/direct-award-justification).

The semantics are 'this previous procedure didn't go well and justifies a direct award'.

**Comment by jpmckinney** [comment]
Hmm, but which of those reasons (1) have a previous procedure and (2) that previous procedure was *not* unsuccessful? For 'bargain', I assume there was no previous procedure, for example.

**Comment by ColinMaudry** [comment]
They are not many, but beside the unsuccesful procedures, "Need for additional works or services by the original contractor" makes me think it's about a previous procedure.

**Comment by ColinMaudry** [comment]
I suggest we simply add one code for this specific case (""Need for additional works or services by the original contractor"), such as 'additionalWork'.

**Comment by jpmckinney** [comment]
I think "justifiesDirectProcedure" is not really about the relationship between processes, but it can perhaps be added to: https://extensions.open-contracting.org/en/extensions/procurementMethodRationaleClassifications/master/

**Comment by ColinMaudry** [comment]
Use the  Procurement method rationale classifications  extension to store the justification code. Free text goes to `procurementMethodRationale`.

**Comment by ColinMaudry** [comment]
Use the  Procurement method rationale classifications  extension to store the justification code. Free text goes to `procurementMethodRationale`.

**Comment by odscjen** [comment]
BT-1252 is part of `cac:ProcessJustification`, the same as BT-135 (Direct Award Justification Text) and BT-136 (Direct Award Justification Code). Only BT-136 is mandatory, BT-135 and BT-1252 may be used.

Current mapping has:
* BT-135 -> `tender.procurementMethodRationale`
* BT-136 -> `tender.procurementMethodRationaleClassifications` with the code in `.id`, the codes label in `.description`

Looking through the justification codes there are 5 that appear to relate to a previous process:
* irregular
* unsuitable

These could both map to a `.relationship` of `unsuccessfulProcess`
* additional
* existing
* repetition

These 3 all read like a previous process was successful and now more is needed and it's easiest to just get it from the previously successful supplier in some way. To keep things simple we could use a code `previousSuccessfulProcess` for all 3? That combined with the specific code from BT-136 should be enough to make it clear how the process in `relatedProcess` relates to the new one?

**Comment by jpmckinney** [comment]
Looking at https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/direct-award-justification

- irregular "Only irregular or unacceptable tenders were received in response to a previous notice. All and only those tenderers of the previous procedure which have satisfied the selection criteria, have not fulfilled the exclusion grounds and have satisfied formal requirements, were included in the negotiations"
- unsuitable "No suitable tenders, requests to participate, or applications were received in response to a previous notice"

Agree that these fit the meaning of 'unsuccessfulProcess'.

- additional "Need for additional works or services by the original contractor"
- existing "Partial replacement or extension of existing supplies or installations by the original supplier ordered under the strict conditions stated in the Directive"
- repetition "New works or services, constituting a repetition of existing works or services and ordered in accordance with the strict conditions stated in the Directive"

I think 'existing' matches 'prior' ("This contracting process is the renewal or replacement of the related prior process.") as they are both about replacement and renewal/extension.

The concepts of "repetition" and "additional" aren't explicitly covered by "prior". That said, I think it's just because when https://github.com/open-contracting/standard/issues/371 was worked on, the only relationships that the authors knew of were replacement and renewal. It would make sense for a generic code like 'prior' to cover all previous successful processes, so I would use that. See https://github.com/open-contracting/standard/issues/1520 for discussion of improving this codelist.

**Comment by jpmckinney** [comment]
Mapped as discussed in last comment.
