### ISSUE TITLE
BT-06, BT-774, BT-775, BT-776: Green or sustainable procurement

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/european-union-support#95]
Potential resources on this topic: 

EU green public procurement criteria: https://ec.europa.eu/environment/gpp/eu_gpp_criteria_en.htm

EU library of use cases: https://ec.europa.eu/environment/gpp/case_group_en.htm

**Comment by jpmckinney** [comment]
Moved the issue and re-opened it in an appropriate repository.

**Comment by duncandewhurst** [comment]
Did you consider using the [sustainability extension](https://extensions.open-contracting.org/en/extensions/sustainability/master/)?

**Comment by odscjen** [comment]
@duncandewhurst thanks for pointing that out, I wasn't aware of that extension. I think it could be a good fit. Mapping tables will still need to be created to extend the sustainabilityGoal.csv codelist.

@jpmckinney do you agree that `sustainability` would be a better place for these BT's than `additionalProcurementCategories`? Innovation (so BT-776 (Innovative procurement)) was discussed in [#1543](https://github.com/open-contracting/standard/issues/1543) and agreed to exist under the broader frame of sustainability so would still fit into this mapping. `sustainability.strategies` would only appear to be possible to fill in for BT-06.

**Comment by odscjen** [comment]
@jpmckinney Suggesting the following mapping tables:

BT-06: [strategic procurement](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/strategic-procurement)

Code | Label | OCDS code | OCDS label/title
-- | -- | -- | --
env-imp | Reduction of environmental impacts | environmental | Reduction of environmental impacts
inn-pur | Innovative purchase | innovation | Innovative purchase
none | None | none | None
soc-obj | Fulfilment of social objectives | social | Fulfilment of social objectives

here I've stuck to `environmental` and `social` as these are already in the sustainability extenstion [sustainabilityGoals](https://extensions.open-contracting.org/en/extensions/sustainability/master/codelists/#sustainabilityGoal.csv) codelist. I've added `innovation` rather than using the existing `economic` as that didn't feel like the right fit based on the discussion in https://github.com/open-contracting/standard/issues/1543. If code used is `none` the guidance will just be to discard this BT.

BT-774: [environmental impact](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/environmental-impact)

Code | Label | OCDS code | OCDS label
-- | -- | -- | --
biodiv-eco | The protection and restoration of biodiversity and ecosystems | environmental.biodiversityProtectionRestoration | The protection and restoration of biodiversity and ecosystems
circ-econ | The transition to a circular economy | environmental.circularEconomy | The transition to a circular economy
clim-adapt | Climate change adaptation | environmental.climateChangeAdaptation | Climate change adaptation
clim-mitig | Climate change mitigation | environmental.climateChangeMitigation | Climate change mitigation
other | Other | environmental | Reduction of environmental impacts
pollu-prev | Pollution prevention and control | environmental.pollutionPrevention | Pollution prevention and control
water-mar | The sustainable use and protection of water and marine resources | environmental.waterResources | The sustainable use and protection of water and marine resources

The 2 part codes are to fit with the sustainability extension pattern. Using `environmental` as `other` works as the general definition of this codelist matches that of `env-imp` in BT-06 which is also mapping to `environmental`. However if it's important to be able to backwards map from OCDS to eForms this would make it impossible to tell which BT this code came from.

BT-775: [social objective](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/social-objective)

Code | Label | OCDS code | OCDS label
-- | -- | -- | --
acc-all | Accessibility for all | social.accessibility | Accessibility for disabled and not disabled persons
et-eq | Ethnic equality | social.ethnicEquality | Ethnic equality
gen-eq | Gender equality | social.genderEquality | Gender equality
hum-right | Human rights due diligence in global supply chains | social.humanRights | Human rights due diligence in global supply chains
opp | Employment opportunities for the long-term unemployed, disadvantaged and/or for persons with disabilities | social.disadvantagedEmploymentOpportunities | Employment opportunities for the long-term unemployed, disadvantaged and/or for persons with disabilities
other | Other | social | Fulfilment of social objectives
work-cond | Fair working conditions | social.fairWorkingConditions | Fair working conditions

As for the environmental codelist I've used the 2 tier codes and `social` for `other`. The same caveat applies.

BT-776: [innovative acquisition](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/innovative-acquisition)

Code | Label | OCDS code | OCDS label
-- | -- | -- | --
mar-nov | The procured works, supplies or services are novel or significantly improved compared to other works, supplies, or services already on the market. | innovation.novel | Procured goods, services or works are novel or significantly improved compared to existing goods, services or works already on the market.
proc-innov | The procured works, supplies, or services entail process innovation | innovation.process | Procured goods, services or works entail process innovation
prod-innov | The procured works, supplies, or services entail product innovation | innovation.product | Procured goods, services or works entail product innovation
rd-act | The procured works, supplies or services involve research and development activities. | innovation.researchDevelopmentActivities | Procured goods, services or works involved research and development activities

**Comment by jpmckinney** [comment]
@yolile I think in the end we put innovation into 'economic', yes? (with 'economic.marketInnovationPromotion'). In that case, the EU's innovation subcodes would be subcodes of 'economic.marketInnovationPromotion'.

Can you also review the new suggested codes?

I don't know if social.disadvantagedEmploymentOpportunities is the same meaning as economic.formalEmploymentPromotion

**Comment by odscjen** [comment]
@yolile have you had a chance to look at this issue yet?

**Comment by yolile** [comment]
> @yolile have you had a chance to look at this issue yet?

Sorry, this was somehow lost in my inbox, thanks for the reminder!

> @yolile I think in the end we put innovation into 'economic', yes? 

Yes.

> Can you also review the new suggested codes?

We could rename "humanRigths" to "humanRightsInSupplyChain", to make it less generic

> I don't know if social.disadvantagedEmploymentOpportunities is the same meaning as economic.formalEmploymentPromotion

I don't think so, as social.disadvantagedEmploymentOpportunities includes "disadvantaged and/or for persons with disabilities" however, informal employment or informal economy is defined differently https://www.ilo.org/employment/units/emp-invest/informal-economy/lang--en/index.htm. As I understand, this one is social and not economic-related because it is related to giving opportunities to persons with some disadvantage.

The one that sounds similar to me is "social.fairWorkingConditions" (defined as "The social objective aims to provide just and equitable working conditions") with "social.laborRightsPromotion" as fair working conditions usually are part of labor rights.

**Comment by odscjen** [comment]
Great, thanks! Those changes to "humanRights" and "social.fairWorkingConditions" make sense.

For "innovation" if it matches to "economic.marketInnovationPromotion" then are we saying that 3 tier codes are acceptable for thecodes in the 'innovation acquisition' table?

Also there's a new business term in this BG, BT-805 Green Procurement Criteria, which takes codes from [gpp-criteria](https://github.com/OP-TED/eForms-SDK/blob/develop/codelists/gpp-criteria.gc). There are 4 codes:
* EU GPP criteria
* National GPP criteria
* No GPP criteria
* Other GPP criteria

These could be mapped as sub-codes of "environmental" but I'm not sure the semantics fit as they're stating the criteria the procurement meets rather than a sustainability goal that is being pursued? This BT might be better placed in `additionalProcurementCategories` which is the current guidance for BT-06?

**Comment by yolile** [comment]
> For "innovation" if it matches to "economic.marketInnovationPromotion" then are we saying that 3 tier codes are acceptable for thecodes in the 'innovation acquisition' table?

I think we can match "mar-nov" with economic.marketInnovationPromotion, and then create a new one under economic for the other 3, eg processInnovation, productInnovation, etc


> Also, there's a new business term in this BG, BT-805 Green Procurement Criteria, which takes codes from [gpp-criteria](https://github.com/OP-TED/eForms-SDK/blob/develop/codelists/gpp-criteria.gc). There are 4 codes:

Hmm, the Sustainability extension also adds two other fields: the boolean `hasSustainabilty` and `sustainability.strategies`. I think this new term can be mapped as a strategy. The strategies codelist is an open one, so I guess for the EU, we could add these ones as additional strategies (and set hasSustainability to true when != "No GPP criteria"). I see the EU GPP criteria includes a series of strategies, one per the product category, e.g., https://ec.europa.eu/environment/gpp/eu_gpp_criteria_en.htm, and the guide says procuring entities may choose which recommended criteria they will use for each tender. So I guess data users will need to rely on other OCDS fields (such as the requirements extension) to know exactly which strategies are being used. If it is possible somehow to know what exact strategy the procuring entity is using, we can include both the general one, e.g., "euGPPCriteria" and "techinicalSpecifications," etc, as the `strategies` field is an array.

**Comment by yolile** [comment]
> I think we can match "mar-nov" with economic.marketInnovationPromotion, and then create a new one under economic for the other 3, eg processInnovation, productInnovation, etc

The other option is just to add the top-level "innovation" code, now that we have a clear use for it

**Comment by yolile** [comment]
For reference, the discussion about "innovation" starts from this comment and below https://github.com/open-contracting-extensions/ocds_sustainability_extension/pull/2#issuecomment-1248565912

**Comment by odscjen** [comment]
Thanks @yollie, using `sustainability.strategies` for BT-805 seems sensible.

> The other option is just to add the top-level "innovation" code, now that we have a clear use for it

For 'innovation' there's also 'inn-pur' from BT-06. The codes in that table appear to act as high level codes with the codes for BT-774, BT-775 and BT-776 being essentially sub-codes. Which does argue for a top-level 'innovation' rather than just putting them all in 'economic' as we'd need 4 more innovation related codes as well as 'mar-nov', something for process, something for product, something for R&D AND something for generic "Innovative purchase".

@jpmckinney This also still leaves the issue of where to map BT-777: Strategic Description. This is used to provide further description of the codes selected in BT-06. Multiple codes, and therefore multiple associated descriptions, are possible. We could just add a `sustainability.description` field, or `sustainability.goals.description` and in the guidance specify that if multiple versions of BT-777 are present then concatenate them all into this `.description` field? But this does separate the descriptions from the code they are attached to in eForms, i.e. a loss of structure.

**Comment by jpmckinney** [comment]
I agree that a top-level innovation code would be a better match for the EU's approach. However, "innovation" is so generic – it doesn't seem like good ontology design to put it at the top. Of course, it may very well be the case that the EU and other jurisdictions don't design ontologies well – or that legislators (or lobbyists, I don't know) get so excited about innovation that it waters down the purpose (sustainability). For now, we'll try to fit their terms into our ontology that at least tries to relate things back to sustainability.

I don't know a good solution for BT-777. We can maybe have the concatenation be "code: description[newline]code: description[etc.]" so that it's easy to reconstruct the structure.

**Comment by jpmckinney** [comment]
I see your edit. Yes, looks good!

**Comment by odscjen** [comment]
guidance.yaml for all BT's mentioned (BT-06, BT-774, BT-775, BT-776, BT-777 and BT-805) is now up-to-date according to the discussion in this issue and mapping tables have been created and uploaded. I'm closing this issue now.
