### ISSUE TITLE
BT-747, BT-752: Check whether to use requirements or selectionCriteria extension

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#97]
See https://github.com/open-contracting/ocds-extensions/issues/170

**Comment by duncandewhurst** [comment]
This is also relevant to the following business terms:

* BT-40
* BT-748
* BT-749
* BT-750
* BT-7531
* BT-7532

Currently, the guidance uses the selectionCriteria extension.

**Comment by duncandewhurst** [comment]
For now just focus on which to use in eForms. Once decided, the issue linked in the description can be addressed.

**Comment by duncandewhurst** [comment]
BT-747 could be expressed using the requirements extension by adding `criterionType` as suggested in https://github.com/open-contracting/ocds-extensions/issues/132.

Due to the limited documentation and examples in the eForms SDK, I'm struggling to assess whether BT-752 could be expressed using the requirements extension. For example, I can find no documentation nor examples of how some of the codes in the [number weight codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-weight) (e.g. `dec-mid`) apply in the context of selection criteria.

The selection criteria extension seems like a safer option since it basically reproduces the eForms model so there shouldn't be any issues using it to express data from eForms. Another benefit of using the selection criteria extension is consistency with the modelling of similar concepts in the award criteria extension.

@jpmckinney are you happy to use the selection criteria on that basis or should I move on to assessing the other business terms listed in https://github.com/open-contracting/european-union-support/issues/97#issuecomment-1254339969 and leave BT-752 as a question mark for now?

**Comment by jpmckinney** [comment]
Hmm, let's go with the selection criteria extension, as it does seem like the safer option. I have a vague memory now that we created the extension because those number weight, etc. fields weren't expressible using the requirements extension – not sure if CCCEV can express them (or the new version of CCCEV).

**Comment by duncandewhurst** [comment]
Sounds good. All the business terms mentioned in this issue are already mapped to the selection criteria extension so I think the issue can be closed.
